### ISSUE TITLE
Wavebreak Media Ltd. Data Engineer Position.

### ISSUE THREAD

**Issue by CalciumNitrade** [christojo7n/2022_IBM_Code_Challenge_Social_service_landplot#1]
Hi, sorry to write here since I couldn't open an issue in data engineer repo. We can delete once you have seen it.

Dear Applicant,

Thank you for your interest for the position of Data Engineer. You have successfully passed the large pool of first round of the applicants.

Forward a link to your GitHub with your attempt at the questions to the following email address: [wbm-rd-jobs@wavebreakmedia.com](mailto:wbm-rd-jobs@wavebreakmedia.com). 

Please also add your CV because we don't even know who you are, only we know your code.

Best Regards,
Can Polat
Senior AI Engineer

**Comment by christojo7n** [comment]
Hi Can,

Glad to hear from you. I have emailed you the CV and Link. Please let me know if you have received it. 

Thanks and regards.

**Comment by CalciumNitrade** [comment]
> Hi Can,
> 
> Glad to hear from you. I have emailed you the CV and Link. Please let me know if you have received it. You can also access the link here. : https://github.com/christojo7n/data-engineer-takehome
> 
> Thanks and regards.

We have received it, thank you.
